version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.20
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
  recommend:
    build:
      dockerfile: Dockerfile
      context: ./recommend
    container_name: recommend
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "redis"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/recommend/node_modules
    env_file:
      - ./recommend/.env.dev
  search:
    build:
      dockerfile: Dockerfile
      context: ./search
    container_name: search
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "redis"
      - "rabbitmq"
      - "elasticsearch"
    volumes:
      - .:/app
      - /app/search/node_modules
    env_file:
      - ./search/.env.dev
  user:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: user
    ports:
      - "8002:8002"
    restart: always
    volumes:
      - .:/app
      - /app/user/node_modules
    env_file:
      - ./user/.env.dev
    depends_on:
      - "rabbitmq"
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - recommend
      - search
      - user
    ports:
      - 80:80

